### ISSUE TITLE
Question about expected runtime

### ISSUE THREAD

**Issue by emjot13** [ldbc/ldbc_snb_bi#146]
When running the benchmark on Tigergraph using: 
- commit: https://github.com/ldbc/ldbc_snb_bi/commit/0734f95541cfa2f912d704e7900491750775eec4 
- pregenerated composite-projected-fk, sf3
- pregenerated factors
  
There were fewer lines written to the results file than usually (about 4000) and I got this comment in the terminal:
```
"1h elapsed for throughput batches, stopping the benchmark."
```
There seemed to not occur any other errors.
Is one hour the expected runtime for sf3?

**Comment by szarnyasg** [comment]
@emjot13 This is normal - the throughput batches should stop after an hour in a benchmark run. See Figure 7.3 in https://ldbcouncil.org/ldbc_snb_docs/ldbc-snb-specification.pdf#page=115.

I can see how the error message is confusing, so I'll amend that later today.
