### ISSUE TITLE
Possibly missing data in pre-generated files bi-sf1000-composite-projected-fk.tar.zst.* 

### ISSUE THREAD

**Issue by krisiasty** [ldbc/ldbc_snb_bi#158]
Not sure whether some csv files are actually missing in pre-generated data files `bi-sf1000-composite-projected-fk.tar.zst.*` or this was intentional, but I can see non-continuous numbering of parts in several directories, for example:

in the `bi-sf1000-composite-projected-fk/graphs/csv/bi/composite-projected-fk/initial_snapshot/dynamic/Person_likes_Comment/` directory there are parts numbered from 00000 to 00355, but parts 00343-00345, 00347, 00350 and 00351 are missing.

in the `bi-sf1000-composite-projected-fk/graphs/csv/bi/composite-projected-fk/initial_snapshot/dynamic/Forum_containerOf_Post/` directory the part 00007 and from 00352 to 00357, and so on...

**As there is no other source to compare and the archives do not contain any checksum files, there is no way to confirm data completeness and integrity.**

**Comment by szarnyasg** [comment]
@krisiasty thanks for pointing out this issue. This is quite unfortunate – the missing files should be there. What likely happened is the following: I generated that data sets in EMR, then I used the `aws s3 cp` command instead of doing repeated runs of `aws s3 sync` (which performs an rsync-style synchronization).

I regenerate the files and upload the correct version.

**Comment by krisiasty** [comment]
@szarnyasg thanks for confirmation. When you regenerate new files, could you please also include some checksums for the content?

**Also, since the data on cloudflare r2 storage for sf1000 in the composite-projected-fk format are incomplete, doesn't that mean all the official benchmark results which used that data, including [LDBC Social Network Benchmark on Tigergraph](https://ldbcouncil.org/benchmarks/snb/LDBC_SNB_BI_20221109_SF1000_tigergraph.pdf), are invalid?** 

How did it pass the audit? Shouldn't they all need to be re-run and re-audited again?

**Comment by szarnyasg** [comment]
Well, not so fast. Let me share my initial thoughts:

1) The R2 repository is LDBC's official repository for BI data sets. So we may decide to elevate this (broken) data set to become a definitive version for the BI benchmark. I'll discuss this possibility with the task force.

2) Unlike SNB Interactive queries, most BI queries do not target an individual Person node, instead, they use data ranges, countries, tags, etc. Therefore, if a few likes and containership edges are missing, the queries will finish successfully – but they will touch on slightly less data.

3) The amount of data missing seems to be small, so its effect on the runtimes is also small, maybe even negligible. I will double-check this

4) 
    > How did it pass the audit?

    At the moment, TigerGraph is the only system (that we have access to) that can run the benchmark at scale factor 1000 – so we cannot cross-validate the results on this scale factor against a system that uses a different serialization layout (`composite-merged-fk`). Instead, the cross-validation happens at smaller scale factors such as SF10 (as prescribed by the auditing guidelines), which TigerGraph passed successfully.

**Comment by szarnyasg** [comment]
I looked into this further and it seems that having missing files is a normal phenomenon - just a symptom of Spark crashing and retrying the job during generation.

I checked it using the `Person_likes_Comment` file in both formats and the number of entities align perfectly:

```bash
$ for FILE in *.csv.gz; do echo "${DIR} $(zcat ${FILE} | tail -n +2 | wc -l)" >> num-entries.csv; done
$ bi-sf1000-composite-merged-fk/graphs/csv/bi/composite-merged-fk/initial_snapshot/dynamic/Person_likes_Comment $ awk '{ sum += $1 } END { print sum }'  num-entries.csv
2249224980

$ for FILE in *.csv.gz; do echo "${DIR} $(zcat ${FILE} | tail -n +2 | wc -l)" >> num-entries.csv; done
$ bi-sf1000-composite-projected-fk/graphs/csv/bi/composite-projected-fk/initial_snapshot/dynamic/Person_likes_Comment $ awk '{ sum += $1 } END { print sum }'  num-entries.csv
2249224980
```

**Comment by krisiasty** [comment]
So, does it mean we can assume the data is complete, just file part numbers are not sequential because of spark crashes?

**Comment by szarnyasg** [comment]
Yes. For the larger scale factors, I remember doing repeated ‘aws s3 sync’
runs to make sure everything is synced.

That said, if you stumble upon any other suspicious cases, let me know and
I’ll look into it.
