### ISSUE TITLE
A guide for adding new implementations?

### ISSUE THREAD

**Issue by karol-brejna-i** [ldbc/ldbc_snb_bi#16]
I see the existing implementations (Cypher, Postgres) follow some folder/files structure.

Could you share the guide (or simple pointers even) on how to propose a new implementation? Which folder/file is responsible for what? What is the execution order, etc.  

Having this kind of instruction could bring some more Graph DBs and make testing/comparing them easier.

**Comment by szarnyasg** [comment]
Hi @karol-brejna-i 

The status of this repository is still a bit fluid (as the benchmark is yet to be finalized and published) but the main responsibilities are as follows: 

```
.
├── batches.py --> apply a batch's worth of inserts/deletes (by default: 1 day)
├── bi.py --> run the queries
├── ddl --> schema definition
├── dml --> insert/delete operations
├── queries --> read queries
├── README.md
├── scratch --> tmp
└── scripts --> scripts to set up the database, load the data, define indices, etc.
```

Do you have a particular system in mind that would like to add?

**Comment by karol-brejna-i** [comment]
Thank you for the prompt response. For now, for me, it's more like general thinking, not having any particular product in mind.
(More like: whenever there is a need to benchmark a graph database for me, I could try to add a new reference implementation.)

Are you aware of any other LDBC SNB implementations? I've seen companies having their own clones/versions of the benchmark...
