### ISSUE TITLE
Link to pre-generated data sets leads to 404

### ISSUE THREAD

**Issue by Dtenwolde** [ldbc/ldbc_snb_bi#169]
Under the header `Data sets` in the README, the following [link](https://github.com/ldbc/ldbc_snb_bi/blob/main/snb-bi-pre-generated-data-sets) leads to a 404 for me

Should it lead to https://ldbcouncil.org/data-sets-surf-repository/ ?

**Comment by szarnyasg** [comment]
It missed the extension. I added it, thanks!
