### ISSUE TITLE
Save precomputation times in Cypher/Umbra scripts

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_bi#59]
Logging does not include these at the moment.

**Comment by szarnyasg** [comment]
For Umbra, reporting individual precomputation times necessitates a small refactor. Currently, all precomputations are in a single file `umbra/dml/apply-precomp.sql`. This should be split to a separate file for each query. @hbirler can you please do this split as part of your current optimization work?

**Comment by hbirler** [comment]
Do you mean only the query specific precomputations or also the general precomputations used by all queries (such as the message table)?

**Comment by szarnyasg** [comment]
Just the query-specific ones

**Comment by hbirler** [comment]
👍
